export interface Phrase {
  id: number;
  phrase: string;
  translation: string; // Placeholder for now
}

export interface CategoryPhrases {
  title: string;
  phrases: Phrase[];
}

export const allPhrases: Record<string, CategoryPhrases> = {
  greetings: {
    title: "Greetings",
    phrases: [
      { id: 1, phrase: "Hello", translation: "Hello" },
      { id: 2, phrase: "Goodbye", translation: "Goodbye" },
      { id: 3, phrase: "Good morning", translation: "Good morning" },
      { id: 4, phrase: "Good afternoon", translation: "Good afternoon" },
      { id: 5, phrase: "Good evening", translation: "Good evening" },
      { id: 6, phrase: "Good night", translation: "Good night" },
      { id: 7, phrase: "How are you?", translation: "How are you?" },
      { id: 8, phrase: "I'm fine, thank you.", translation: "I'm fine, thank you." },
      { id: 9, phrase: "What's your name?", translation: "What's your name?" },
      { id: 10, phrase: "My name is...", translation: "My name is..." },
      { id: 11, phrase: "Nice to meet you.", translation: "Nice to meet you." },
      { id: 12, phrase: "See you later.", translation: "See you later." },
      { id: 13, phrase: "Excuse me.", translation: "Excuse me." },
      { id: 14, phrase: "I'm sorry.", translation: "I'm sorry." },
      { id: 15, phrase: "Thank you.", translation: "Thank you." },
      { id: 16, phrase: "You're welcome.", translation: "You're welcome." },
      { id: 17, phrase: "Please.", translation: "Please." },
      { id: 18, phrase: "Yes.", translation: "Yes." },
      { id: 19, phrase: "No.", translation: "No." },
      { id: 20, phrase: "I don't understand.", translation: "I don't understand." },
      { id: 21, phrase: "Could you speak slower?", translation: "Could you speak slower?" },
      { id: 22, phrase: "How do you say...?", translation: "How do you say...?" },
      { id: 23, phrase: "Where are you from?", translation: "Where are you from?" },
      { id: 24, phrase: "I'm from...", translation: "I'm from..." },
      { id: 25, phrase: "Have a nice day.", translation: "Have a nice day." },
      { id: 26, phrase: "Take care.", translation: "Take care." },
      { id: 27, phrase: "What's up?", translation: "What's up?" },
      { id: 28, phrase: "Not much.", translation: "Not much." },
      { id: 29, phrase: "How's it going?", translation: "How's it going?" },
      { id: 30, phrase: "It's going well.", translation: "It's going well." },
    ],
  },
  transport: {
    title: "Transport",
    phrases: [
      { id: 1, phrase: "Where is the nearest bus stop?", translation: "Where is the nearest bus stop?" },
      { id: 2, phrase: "A ticket to [destination], please.", translation: "A ticket to [destination], please." },
      { id: 3, phrase: "One-way or round trip?", translation: "One-way or round trip?" },
      { id: 4, phrase: "How much is the fare?", translation: "How much is the fare?" },
      { id: 5, phrase: "Does this bus go to [destination]?", translation: "Does this bus go to [destination]?" },
      { id: 6, phrase: "What time does the next train leave?", translation: "What time does the next train leave?" },
      { id: 7, phrase: "Which platform is it?", translation: "Which platform is it?" },
      { id: 8, phrase: "Is this seat taken?", translation: "Is this seat taken?" },
      { id: 9, phrase: "Can you tell me when we get to [stop]?", translation: "Can you tell me when we get to [stop]?" },
      { id: 10, phrase: "I'd like to rent a car.", translation: "I'd like to rent a car." },
      { id: 11, phrase: "Where can I get a taxi?", translation: "Where can I get a taxi?" },
      { id: 12, phrase: "Please take me to this address.", translation: "Please take me to this address." },
      { id: 13, phrase: "How long will it take to get there?", translation: "How long will it take to get there?" },
      { id: 14, phrase: "Please stop here.", translation: "Please stop here." },
      { id: 15, phrase: "I missed my stop.", translation: "I missed my stop." },
      { id: 16, phrase: "Is there a direct train?", translation: "Is there a direct train?" },
      { id: 17, phrase: "Do I need to change trains?", translation: "Do I need to change trains?" },
      { id: 18, phrase: "Where is the ticket office?", translation: "Where is the ticket office?" },
      { id: 19, phrase: "Can I have a map of the subway?", translation: "Can I have a map of the subway?" },
      { id: 20, phrase: "Is this the right way to...?", translation: "Is this the right way to...?" },
      { id: 21, phrase: "I'm lost.", translation: "I'm lost." },
      { id: 22, phrase: "How do I get to the airport?", translation: "How do I get to the airport?" },
      { id: 23, phrase: "What's the next stop?", translation: "What's the next stop?" },
      { id: 24, phrase: "Can I pay with a credit card?", translation: "Can I pay with a credit card?" },
      { id: 25, phrase: "Is there a discount for children?", translation: "Is there a discount for children?" },
      { id: 26, phrase: "I need to buy a travel card.", translation: "I need to buy a travel card." },
      { id: 27, phrase: "Where is the baggage claim?", translation: "Where is the baggage claim?" },
      { id: 28, phrase: "My luggage is missing.", translation: "My luggage is missing." },
      { id: 29, phrase: "When is the last train?", translation: "When is the last train?" },
      { id: 30, phrase: "Is the train on time?", translation: "Is the train on time?" },
    ],
  },
  hotel: {
    title: "Hotel",
    phrases: [
      { id: 1, phrase: "I have a reservation.", translation: "I have a reservation." },
      { id: 2, phrase: "I'd like to check in.", translation: "I'd like to check in." },
      { id: 3, phrase: "I'd like to check out.", translation: "I'd like to check out." },
      { id: 4, phrase: "Can I have the key, please?", translation: "Can I have the key, please?" },
      { id: 5, phrase: "What time is breakfast?", translation: "What time is breakfast?" },
      { id: 6, phrase: "What time is check-out?", translation: "What time is check-out?" },
      { id: 7, phrase: "Can I have a wake-up call at [time]?", translation: "Can I have a wake-up call at [time]?" },
      { id: 8, phrase: "Is there Wi-Fi in the room?", translation: "Is there Wi-Fi in the room?" },
      { id: 9, phrase: "What's the Wi-Fi password?", translation: "What's the Wi-Fi password?" },
      { id: 10, phrase: "My room key isn't working.", translation: "My room key isn't working." },
      { id: 11, phrase: "The air conditioning isn't working.", translation: "The air conditioning isn't working." },
      { id: 12, phrase: "Can I have an extra towel?", translation: "Can I have an extra towel?" },
      { id: 13, phrase: "Where is the elevator?", translation: "Where is the elevator?" },
      { id: 14, phrase: "Is breakfast included?", translation: "Is breakfast included?" },
      { id: 15, phrase: "Can you recommend a good restaurant?", translation: "Can you recommend a good restaurant?" },
      { id: 16, phrase: "I'd like to order room service.", translation: "I'd like to order room service." },
      { id: 17, phrase: "Can I store my luggage here?", translation: "Can I store my luggage here?" },
      { id: 18, phrase: "Do you have a map of the city?", translation: "Do you have a map of the city?" },
      { id: 19, phrase: "What floor is my room on?", translation: "What floor is my room on?" },
      { id: 20, phrase: "The room is too noisy.", translation: "The room is too noisy." },
      { id: 21, phrase: "I need a doctor.", translation: "I need a doctor." },
      { id: 22, phrase: "Is there a gym?", translation: "Is there a gym?" },
      { id: 23, phrase: "Can you call a taxi for me?", translation: "Can you call a taxi for me?" },
      { id: 24, phrase: "I've lost my room key.", translation: "I've lost my room key." },
      { id: 25, phrase: "Do you have an adapter?", translation: "Do you have an adapter?" },
      { id: 26, phrase: "Is tap water safe to drink?", translation: "Is tap water safe to drink?" },
      { id: 27, phrase: "My room hasn't been cleaned.", translation: "My room hasn't been cleaned." },
      { id: 28, phrase: "Can I have a late check-out?", translation: "Can I have a late check-out?" },
      { id: 29, phrase: "I'd like to extend my stay.", translation: "I'd like to extend my stay." },
      { id: 30, phrase: "What is the hotel's address?", translation: "What is the hotel's address?" },
    ],
  },
  dining: {
    title: "Dining",
    phrases: [
      { id: 1, phrase: "A table for two, please.", translation: "A table for two, please." },
      { id: 2, phrase: "I'd like to see the menu, please.", translation: "I'd like to see the menu, please." },
      { id: 3, phrase: "What do you recommend?", translation: "What do you recommend?" },
      { id: 4, phrase: "I'm a vegetarian.", translation: "I'm a vegetarian." },
      { id: 5, phrase: "I'm allergic to nuts.", translation: "I'm allergic to nuts." },
      { id: 6, phrase: "I'll have this.", translation: "I'll have this." },
      { id: 7, phrase: "Can I have a glass of water?", translation: "Can I have a glass of water?" },
      { id: 8, phrase: "The bill, please.", translation: "The bill, please." },
      { id: 9, phrase: "Can I pay by credit card?", translation: "Can I pay by credit card?" },
      { id: 10, phrase: "Is service included?", translation: "Is service included?" },
      { id: 11, phrase: "We'd like to order now.", translation: "We'd like to order now." },
      { id: 12, phrase: "What's the soup of the day?", translation: "What's the soup of the day?" },
      { id: 13, phrase: "Is this dish spicy?", translation: "Is this dish spicy?" },
      { id: 14, phrase: "Can I have this without onions?", translation: "Can I have this without onions?" },
      { id: 15, phrase: "This isn't what I ordered.", translation: "This isn't what I ordered." },
      { id: 16, phrase: "Everything was delicious.", translation: "Everything was delicious." },
      { id: 17, phrase: "Can we have separate bills?", translation: "Can we have separate bills?" },
      { id: 18, phrase: "Do you have a high chair?", translation: "Do you have a high chair?" },
      { id: 19, phrase: "Where is the restroom?", translation: "Where is the restroom?" },
      { id: 20, phrase: "I'd like to make a reservation.", translation: "I'd like to make a reservation." },
      { id: 21, phrase: "Is this table reserved?", translation: "Is this table reserved?" },
      { id: 22, phrase: "What are your opening hours?", translation: "What are your opening hours?" },
      { id: 23, phrase: "Can I get this to go?", translation: "Can I get this to go?" },
      { id: 24, phrase: "I'll have the same thing.", translation: "I'll have the same thing." },
      { id: 25, phrase: "Another one, please.", translation: "Another one, please." },
      { id: 26, phrase: "Keep the change.", translation: "Keep the change." },
      { id: 27, phrase: "What kind of beer do you have?", translation: "What kind of beer do you have?" },
      { id: 28, phrase: "A bottle of red wine, please.", translation: "A bottle of red wine, please." },
      { id: 29, phrase: "Do you have any local specialties?", translation: "Do you have any local specialties?" },
      { id: 30, phrase: "Is there a children's menu?", translation: "Is there a children's menu?" },
    ],
  },
  directions: {
    title: "Directions",
    phrases: [
      { id: 1, phrase: "Excuse me, where is the museum?", translation: "Excuse me, where is the museum?" },
      { id: 2, phrase: "How do I get to this address?", translation: "How do I get to this address?" },
      { id: 3, phrase: "Is it far from here?", translation: "Is it far from here?" },
      { id: 4, phrase: "Can you show me on the map?", translation: "Can you show me on the map?" },
      { id: 5, phrase: "Turn left.", translation: "Turn left." },
      { id: 6, phrase: "Turn right.", translation: "Turn right." },
      { id: 7, phrase: "Go straight ahead.", translation: "Go straight ahead." },
      { id: 8, phrase: "It's on the corner.", translation: "It's on the corner." },
      { id: 9, phrase: "It's next to the bank.", translation: "It's next to the bank." },
      { id: 10, phrase: "It's opposite the park.", translation: "It's opposite the park." },
      { id: 11, phrase: "I'm looking for the post office.", translation: "I'm looking for the post office." },
      { id: 12, phrase: "Is there a pharmacy nearby?", translation: "Is there a pharmacy nearby?" },
      { id: 13, phrase: "How far is it to the airport?", translation: "How far is it to the airport?" },
      { id: 14, phrase: "Can I walk there?", translation: "Can I walk there?" },
      { id: 15, phrase: "We are here.", translation: "We are here." },
      { id: 16, phrase: "You are going the wrong way.", translation: "You are going the wrong way." },
      { id: 17, phrase: "It's about a 10-minute walk.", translation: "It's about a 10-minute walk." },
      { id: 18, phrase: "Where is the nearest ATM?", translation: "Where is the nearest ATM?" },
      { id: 19, phrase: "Follow the signs for...", translation: "Follow the signs for..." },
      { id: 20, phrase: "Go past the traffic lights.", translation: "Go past the traffic lights." },
      { id: 21, phrase: "Take the second exit at the roundabout.", translation: "Take the second exit at the roundabout." },
      { id: 22, phrase: "It's just around the corner.", translation: "It's just around the corner." },
      { id: 23, phrase: "Cross the bridge.", translation: "Cross the bridge." },
      { id: 24, phrase: "Go up the hill.", translation: "Go up the hill." },
      { id: 25, phrase: "Go down the stairs.", translation: "Go down the stairs." },
      { id: 26, phrase: "Which way is north?", translation: "Which way is north?" },
      { id: 27, phrase: "I'm trying to find the city center.", translation: "I'm trying to find the city center." },
      { id: 28, phrase: "Is this the bus to the beach?", translation: "Is this the bus to the beach?" },
      { id: 29, phrase: "You can't miss it.", translation: "You can't miss it." },
      { id: 30, phrase: "It's in front of you.", translation: "It's in front of you." },
    ],
  },
  shopping: {
    title: "Shopping",
    phrases: [
      { id: 1, phrase: "How much is this?", translation: "How much is this?" },
      { id: 2, phrase: "Can I try this on?", translation: "Can I try this on?" },
      { id: 3, phrase: "Where are the fitting rooms?", translation: "Where are the fitting rooms?" },
      { id: 4, phrase: "Do you have this in a different size?", translation: "Do you have this in a different size?" },
      { id: 5, phrase: "Do you have this in a different color?", translation: "Do you have this in a different color?" },
      { id: 6, phrase: "I'm just looking, thank you.", translation: "I'm just looking, thank you." },
      { id: 7, phrase: "I'll take it.", translation: "I'll take it." },
      { id: 8, phrase: "Can I pay with a credit card?", translation: "Can I pay with a credit card?" },
      { id: 9, phrase: "Do you accept cash?", translation: "Do you accept cash?" },
      { id: 10, phrase: "Can I have a receipt, please?", translation: "Can I have a receipt, please?" },
      { id: 11, phrase: "Is this on sale?", translation: "Is this on sale?" },
      { id: 12, phrase: "Can I have a bag, please?", translation: "Can I have a bag, please?" },
      { id: 13, phrase: "What are your opening hours?", translation: "What are your opening hours?" },
      { id: 14, phrase: "I'm looking for a souvenir.", translation: "I'm looking for a souvenir." },
      { id: 15, phrase: "This is too expensive.", translation: "This is too expensive." },
      { id: 16, phrase: "Can you give me a discount?", translation: "Can you give me a discount?" },
      { id: 17, phrase: "I'd like to return this.", translation: "I'd like to return this." },
      { id: 18, phrase: "Do you have a smaller/larger size?", translation: "Do you have a smaller/larger size?" },
      { id: 19, phrase: "Is this tax-free?", translation: "Is this tax-free?" },
      { id: 20, phrase: "Where can I find groceries?", translation: "Where can I find groceries?" },
      { id: 21, phrase: "I'm looking for the men's/women's section.", translation: "I'm looking for the men's/women's section." },
      { id: 22, phrase: "Can you gift wrap this for me?", translation: "Can you gift wrap this for me?" },
      { id: 23, phrase: "What is this made of?", translation: "What is this made of?" },
      { id: 24, phrase: "Is it handmade?", translation: "Is it handmade?" },
      { id: 25, phrase: "I'm paying separately.", translation: "I'm paying separately." },
      { id: 26, phrase: "Where is the checkout?", translation: "Where is the checkout?" },
      { id: 27, phrase: "Do you ship internationally?", translation: "Do you ship internationally?" },
      { id: 28, phrase: "This is a gift.", translation: "This is a gift." },
      { id: 29, phrase: "I'm looking for something cheaper.", translation: "I'm looking for something cheaper." },
      { id: 30, phrase: "What is your return policy?", translation: "What is your return policy?" },
    ],
  },
  emergency: {
    title: "Emergency",
    phrases: [
      { id: 1, phrase: "Help!", translation: "Help!" },
      { id: 2, phrase: "I need a doctor.", translation: "I need a doctor." },
      { id: 3, phrase: "Call the police.", translation: "Call the police." },
      { id: 4, phrase: "Call an ambulance.", translation: "Call an ambulance." },
      { id: 5, phrase: "There's been an accident.", translation: "There's been an accident." },
      { id: 6, phrase: "I've lost my passport.", translation: "I've lost my passport." },
      { id: 7, phrase: "I've lost my wallet.", translation: "I've lost my wallet." },
      { id: 8, phrase: "Someone stole my bag.", translation: "Someone stole my bag." },
      { id: 9, phrase: "I'm lost.", translation: "I'm lost." },
      { id: 10, phrase: "I don't feel well.", translation: "I don't feel well." },
      { id: 11, phrase: "Where is the nearest hospital?", translation: "Where is the nearest hospital?" },
      { id: 12, phrase: "I need to go to the embassy.", translation: "I need to go to the embassy." },
      { id: 13, phrase: "Is there a fire?", translation: "Is there a fire?" },
      { id: 14, phrase: "I can't breathe.", translation: "I can't breathe." },
      { id: 15, phrase: "It's an emergency.", translation: "It's an emergency." },
      { id: 16, phrase: "I need help, please.", translation: "I need help, please." },
      { id: 17, phrase: "My child is missing.", translation: "My child is missing." },
      { id: 18, phrase: "I'm having an allergic reaction.", translation: "I'm having an allergic reaction." },
      { id: 19, phrase: "I've been robbed.", translation: "I've been robbed." },
      { id: 20, phrase: "What is the emergency number?", translation: "What is the emergency number?" },
      { id: 21, phrase: "I've been injured.", translation: "I've been injured." },
      { id: 22, phrase: "Please hurry.", translation: "Please hurry." },
      { id: 23, phrase: "I'm bleeding.", translation: "I'm bleeding." },
      { id: 24, phrase: "I think I broke my arm.", translation: "I think I broke my arm." },
      { id: 25, phrase: "I've been bitten by an animal.", translation: "I've been bitten by an animal." },
      { id: 26, phrase: "I feel dizzy.", translation: "I feel dizzy." },
      { id: 27, phrase: "I need a translator.", translation: "I need a translator." },
      { id: 28, phrase: "Can you help me?", translation: "Can you help me?" },
      { id: 29, phrase: "I'm locked out of my room.", translation: "I'm locked out of my room." },
      { id: 30, phrase: "My phone is dead.", translation: "My phone is dead." },
    ],
  },
  basics: {
    title: "Basics",
    phrases: [
      { id: 1, phrase: "One", translation: "One" },
      { id: 2, phrase: "Two", translation: "Two" },
      { id: 3, phrase: "Three", translation: "Three" },
      { id: 4, phrase: "Four", translation: "Four" },
      { id: 5, phrase: "Five", translation: "Five" },
      { id: 6, phrase: "Six", translation: "Six" },
      { id: 7, phrase: "Seven", translation: "Seven" },
      { id: 8, phrase: "Eight", translation: "Eight" },
      { id: 9, phrase: "Nine", translation: "Nine" },
      { id: 10, phrase: "Ten", translation: "Ten" },
      { id: 11, phrase: "What time is it?", translation: "What time is it?" },
      { id: 12, phrase: "Today", translation: "Today" },
      { id: 13, phrase: "Yesterday", translation: "Yesterday" },
      { id: 14, phrase: "Tomorrow", translation: "Tomorrow" },
      { id: 15, phrase: "Monday", translation: "Monday" },
      { id: 16, phrase: "Tuesday", translation: "Tuesday" },
      { id: 17, phrase: "Wednesday", translation: "Wednesday" },
      { id: 18, phrase: "Thursday", translation: "Thursday" },
      { id: 19, phrase: "Friday", translation: "Friday" },
      { id: 20, phrase: "Saturday", translation: "Saturday" },
      { id: 21, phrase: "Sunday", translation: "Sunday" },
      { id: 22, phrase: "I would like...", translation: "I would like..." },
      { id: 23, phrase: "How much?", translation: "How much?" },
      { id: 24, phrase: "Where is the toilet?", translation: "Where is the toilet?" },
      { id: 25, phrase: "I don't know.", translation: "I don't know." },
      { id: 26, phrase: "Can you repeat that?", translation: "Can you repeat that?" },
      { id: 27, phrase: "What is this?", translation: "What is this?" },
      { id: 28, phrase: "I need...", translation: "I need..." },
      { id: 29, phrase: "Water", translation: "Water" },
      { id: 30, phrase: "Food", translation: "Food" },
    ],
  },
};